apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-k3s.fullname" . }}
  labels:
    {{- include "aws-k3s.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aws-k3s.selectorLabels" . | nindent 4 }}
