---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # namespace: aws-k3s-terraform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: 940432861086.dkr.ecr.eu-west-2.amazonaws.com/app1
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  # namespace: aws-k3s-terraform
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app1